sudo: false
language: php
php:
    - 7
    - 7.1
before_script:
    - composer self-update
    - composer install --prefer-source
script:
    - chmod -R 777 tests/logs tests/tmp
    - ./vendor/bin/phpunit

